### ISSUE TITLE
CCTV16能更新一下吗

### ISSUE THREAD

**Issue by a1083036482** [wuwentao/bj-unicom-iptv#11]
CCTV16能更新一下吗

**Comment by wuwentao** [comment]
抱歉，没有找到北京联通合适的CCTV16直播源，目前机顶盒里面有这个台吗？或者说是其他地方？或网络渠道的来源？
如果有的话可以加进去呢，因为我发现其他北京联通的IPTV也没有这个直播源地址
@a1083036482

**Comment by wuwentao** [comment]
@a1083036482 
已增加北京联通CCTV16 4K节目源，请更新列表！
