### ISSUE TITLE
tivimate切台确实快，但对于group-title="[高清]央视;少儿"这种支持不够

### ISSUE THREAD

**Issue by wentijianihao** [wuwentao/bj-unicom-iptv#15]
分组显示成：[高清]央视;少儿，    特别扭的。
别的app就能很好支持，分别放在两个分组里。

**Comment by wuwentao** [comment]
对的，这个分别放进二个组里了，这个tivimate app不支持多分组？
切台快和app还有很大关系？还真没试过，一直在用kodi，就没倒腾了

**Comment by wentijianihao** [comment]
> 对的，这个分别放进二个组里了，这个tivimate app不支持多分组？ 切台快和app还有很大关系？还真没试过，一直在用kodi，就没倒腾了

基本秒切，比之前用的“iptv“快多了。没用过kodi的电视功能

**Comment by wuwentao** [comment]
kodi基本也是秒切，一直在用，分号间隔的，也会自动在二个不同的分组里面显示，epg台标也都支持！

**Comment by wentijianihao** [comment]
> kodi基本也是秒切，一直在用，分号间隔的，也会自动在二个不同的分组里面显示，epg台标也都支持！

回去试试
