### ISSUE TITLE
请问没有买联通的IPTV服务的话可以看联通组播吗？

### ISSUE THREAD

**Issue by jinghua625** [wuwentao/bj-unicom-iptv#18]
请问没有买联通的IPTV服务的话可以看联通组播吗？

**Comment by jinghua625** [comment]
用的是北京联通的线路

**Comment by wuwentao** [comment]
@jinghua625 可以的，没问题，仔细看文档和说明进行操作即可

**Comment by jinghua625** [comment]
感谢，放假好好研究一下

**Comment by wuwentao** [comment]
close

**Comment by jinghua625** [comment]
联通已经成功了，开始研究移动的，特来感谢！

**Comment by wuwentao** [comment]
移动官方的源比较垃圾，不是组播，单播地址单独认证……所以不大靠谱！

**Comment by jinghua625** [comment]
嗯嗯，看了您的移动源也找了恩山里的，都是互联网的源。以前也用过，如果只是m3u8结尾的失效很快，我没开通移动的IPTV，要不就能抓抓看他们是通过什么地址提供服务的了。

**Comment by wuwentao** [comment]
我也有个移动的光纤宽带， 但是没开IPTV，没啥用，这种单播源很快就得放弃治疗了，没有组播，服务器撑不住，用户也撑不住，都是垃圾
