### ISSUE TITLE
熊猫台没有了。。。

### ISSUE THREAD

**Issue by lixinf** [wuwentao/bj-unicom-iptv#19]

**Comment by wuwentao** [comment]
抱歉，这周不在北京，周六日回去看看状态……

**Comment by wuwentao** [comment]
感谢反馈，上次回家看了一下确实失效了，没来得及更新列表！
今天抽空暂时先移出列表了！

**Comment by lixinf** [comment]
搞好了吗？发送自我的盖乐世
-------- 原始信息 --------发件人： Wentao Wu ***@***.***> 日期: 2022/3/12  14:47  (GMT+08:00) 收件人： wuwentao/bj-unicom-iptv ***@***.***> 抄送： lixinf ***@***.***>, Author ***@***.***> 主题： Re: [wuwentao/bj-unicom-iptv] 熊猫台没有了。。。 (Issue #19) 
Closed #19.

**Comment by wuwentao** [comment]
@lixinf 您是希望恢复这个节目源啊？不是剔除失效的？

**Comment by lixinf** [comment]
当然是恢复啊，可爱的熊猫多有意思啊发送自我的盖乐世
-------- 原始信息 --------发件人： Wentao Wu ***@***.***> 日期: 2022/3/23  09:53  (GMT+08:00) 收件人： wuwentao/bj-unicom-iptv ***@***.***> 抄送： lixinf ***@***.***>, Mention ***@***.***> 主题： Re: [wuwentao/bj-unicom-iptv] 熊猫台没有了。。。 (Issue #19) 

@lixinf 您是希望恢复这个节目源啊？不是剔除失效的？

**Comment by wuwentao** [comment]
@lixinf 明白意思了，不过这个问题，有点尴尬，您用机顶盒看还有这个频道吗？
首先得先确认一下现在联通IPTV的机顶盒里是否有这个对应的频道，如果有的话，那没问题！
如果机顶盒里都没有这个频道了，恐怕无能为力了，这个得找联通客服反馈去重新开通了！

**Comment by lixinf** [comment]
联通的机顶盒还有这个频道啊。。。
















在 2022-03-25 12:15:58，"Wentao Wu" ***@***.***> 写道：

@lixinf 明白意思了，不过这个问题，有点尴尬，您用机顶盒看还有这个频道吗？
首先得先确认一下现在联通IPTV的机顶盒里是否有这个对应的频道，如果有的话，那没问题！
如果机顶盒里都没有这个频道了，恐怕无能为力了，这个得找联通客服反馈去重新开通了！

**Comment by wuwentao** [comment]
@lixinf OK，家里电视和机顶盒每天被小孩和老人“霸占”，没有机会挨个频道看一眼，我抽空扫一下新的地址，晚些更新！

**Comment by lixinf** [comment]
好的，更新了通知一下吧，提前谢谢啦发送自我的盖乐世
-------- 原始信息 --------发件人： Wentao Wu ***@***.***> 日期: 2022/3/25  12:16  (GMT+08:00) 收件人： wuwentao/bj-unicom-iptv ***@***.***> 抄送： lixinf ***@***.***>, Mention ***@***.***> 主题： Re: [wuwentao/bj-unicom-iptv] 熊猫台没有了。。。 (Issue #19) 
@lixinf 明白意思了，不过这个问题，有点尴尬，您用机顶盒看还有这个频道吗？
首先得先确认一下现在联通IPTV的机顶盒里是否有这个对应的频道，如果有的话，那没问题！
如果机顶盒里都没有这个频道了，恐怕无能为力了，这个得找联通客服反馈去重新开通了！

**Comment by wuwentao** [comment]
@lixinf 不好意思，我翻边联通IPTV的界面列表（机顶盒自带的），也没发现任何熊猫台，请问您怎么确定联通机顶盒里面有？哪个区？多少频道号？

**Comment by lixinf** [comment]
还在啊，联通机顶盒北京朝阳区， 324 熊猫频道。


















在 2022-04-06 10:10:18，"Wentao Wu" ***@***.***> 写道：

@lixinf 不好意思，我翻边联通IPTV的界面列表（机顶盒自带的），也没发现任何熊猫台，请问您怎么确定联通机顶盒里面有？哪个区？多少频道号？

**Comment by wuwentao** [comment]
@lixinf 忘了给您回复，我这边没有您说的这个熊猫台节目源，机顶盒里没有……
所以，抓不到对应的频道，或者说您直接看看之前删除的那个源，是否可以播放？如果可以，咱们可以恢复之前的节目源地址即可。
