### ISSUE TITLE
再向 repo 主安利一波脚本

### ISSUE THREAD

**Issue by huxuan** [wuwentao/bj-unicom-iptv#2]
RT，代码在此：https://github.com/huxuan/iptvtools

使用命令
```
iptv-filter \
-i https://gist.githubusercontent.com/sdhzdmzzl/93cf74947770066743fff7c7f4fc5820/raw/0be4160f4024320f23daad65bce79e606da47995/bj-unicom-iptv.m3u \
-t http://epg.51zmt.top:8000/test.m3u \
--min-height 1080 \
-u http://192.168.50.1:8888
-c config.json
```

其中
- `-i` 是输入，任意的 m3u 文件或者url 都可以
- `-t` 是模板，主要是[这个大神的网站](http://epg.51zmt.top:8000/)上提供的
- `-u` 是 udpxy 的前缀
- `-c config.json` 是一个 json 配置，主要用来统一频道名称和匹配信息的，[传送门在这里](https://github.com/huxuan/iptvtools/blob/master/config.json) 

如果出现很多频道连不上的情况可能是访问太频繁了，可以添加参数 `-I 10`来让每次请求之间间隔 10s

这样得到的 m3u 文件：https://gist.github.com/huxuan/49944d454e1aad26b93977df80c4a32c

主要好处是：

1. 配合如 kodi 之类的播放器里的 epg 信息可以显示台标还有节目单
2. 直接 filter 掉清晰度低的源，比较适合给 4K Android TV 用

如果不嫌弃，repo 主可以考虑用这个方式生成播放列表然后维护起来分享给大家~

P.S. 我家死活连不上朝阳电视台，难道因为是在海淀的缘故 - -

**Comment by wuwentao** [comment]
收到，多谢，感谢分享，周六日有空我再慢慢试试，然后整理一下结果，需要时间来慢慢积累和整理，哈哈！
这个带台标的，我用PC上简单试了试，Mac上好几个播放器都不支持这种，哈哈哈，应该得kodi之类的电视盒子！
PS: 朝阳电视台我也打不开，房山和密云是可以打开的，坐标昌平回龙观

**Comment by huxuan** [comment]
哈哈，献上几张不是很走心的截图~

看来 repo 主没折腾过 kodi？那个也是跨平台的开源软件，以前在学校看 iptv 就靠它，没想到还靠着他没有办联通的 iptv 业务就也可以看电视了，省了一笔安装费 

![screen](https://user-images.githubusercontent.com/726061/76057723-4d5ed000-5fb5-11ea-97da-283c45646846.png)
![screen1](https://user-images.githubusercontent.com/726061/76057727-52bc1a80-5fb5-11ea-9c6f-7608998175bc.png)
![screen2](https://user-images.githubusercontent.com/726061/76057735-5485de00-5fb5-11ea-99bb-3aa6712f748a.png)

**Comment by wuwentao** [comment]
@huxuan 
是的，一直只是听说过kodi，好多刷机的, 也是跑kodi ，十几年前就刷路由，拆芯片，编版本，玩腻了，不再折腾好久好久了，现在就是看看IPTV就算了
那么问题来了：敢问大神，kodi相比之下有啥优势？加载这些播放列表后，会比普通播放器额外增加哪些附加功能？还是就普通电视盒子刷机，去掉官方的广告啥的？
我记得恩山论坛里是可以额外支持节目回放，其他还有啥子优点？请指点一下，看看是否有值得一试的功能，哈哈

**Comment by huxuan** [comment]
不知道 repo 主是不是对 kodi 有误解，kodi 只是一个软件，几乎所有电子设备(win / mac / linux / android / ios) 上都能安装，并不需要什么折腾呀，顶多就是配置配置啥的，主要还是用着方便吧，尤其是在 Android TV 上，我没找到其他更方便看 IPTV 的播放器了。而且 Kodi 还支持管理电影、电视剧、音乐啥的，家里有 nas 的直接开个 nfs/smb 共享然后导入一下可以很方便的浏览，它的实际定位是 media center。

再奉上几张截图，内容请无视，有些剧集啥的都是挂 PT 刷流量下的，不代表个人喜好 - -

![screen1](https://user-images.githubusercontent.com/726061/76059426-c5c79000-5fb9-11ea-862a-d6aae76cbaf3.png)

![screen](https://user-images.githubusercontent.com/726061/76059409-b8120a80-5fb9-11ea-9f1b-c4cfdb09761b.png)

**Comment by wuwentao** [comment]
不是有误解，周五快放假了，继续闲聊会：
我就是指这个软件功能，个人感觉主要的使用场景还是倾向于Android TV和电视盒子，在PC端，例如Mac和Windows，从播放视频+IPTV方面，依然还是Portplayer （Windows）, IINA/VLC(Mac OS)更简单方便（例如：多开，记忆窗口大小，最小化自带暂停，快速暂停，切换，任意缩放，截屏，录像等等控制功能）……

您的需求： 不仅仅是播放视频+ IPTV（居然不购买IPTV都能播放，确实给力），额外附带NAS存储有各种本地高清视频源，只用PC端播放器的问题可能是不方便管理，kodi就附带各种高级属性和方便性出来了，这类节目片源选择和管理使用会更方便。

我用电视/机顶盒方面的需求（确实是没有啥需求和动力来选择折腾kodi）：
1. 电视播放IPTV（我直接用联通宽带赠送的IPTV机顶盒，自带IPTV源，不需要折腾了……）
2. 本地存储视频源播放+视频媒体管理等（确实没有，SSD存不下太多4K，哈哈，偶尔Airplay投屏播放）
3. 去除各种广告和花里胡哨的东西？
4. 各种智能电视或者电视外挂播放功能，用kodi播放IPTV（直接用联通IPTV机顶盒了，也没机会折腾了）

除此之外，我其实有iPAD，iPhone之类的播放需求，但都用不了kodi(需越狱，不考虑)……

所以: 并不是说kodi不好，确实是非常流弊的开源软件，但针对普通用户来说，PC端确实不好切入，ios端也没法切入，kodi剩下更多使用场景还是在电视盒子，但电视盒子都自带官方软件和OS了，kodi需要app安装权限，所以只是想表达：从个人需求和当前实际使用场景来说，目前确实没有用上这个流弊的软件，导致对kodi一直文盲中……（我的片源太少+看片时间短+搬砖时间多，哈哈）

最后： kodi配置文件不是说不折腾，用不用kodi是一回事，生成配置文件是另外一回事，随后我还是会抽空试试滴!

PS:  我个人是不倒腾NAS，因为NAS折腾的成本太高(只能羡慕折腾NAS的土豪们，以及本地高清视频源，哈哈)，还有访问速度得局限于家中。
我是云服务重度用户，Apple相关的都在iCloud，Mac端附带Google Drive File Strem/Google Backup and Sync,  其次还有一个OneDrive是用公司的，所有数据都是云端了(免费赠送百度云备胎，纯相册备份，限速太垃圾，基本不用)，所以我整个电脑或手机丢掉，都能立刻能云端(或者Web上）满血复活，几块移动硬盘都在吃灰，迅雷会员好像很早就续费到2022年了，一样吃灰中，百度云反倒挺香……

**Comment by huxuan** [comment]
哈哈，感觉有点 OT 了，把 issue 当论坛了会不会不太好。

家里领导的主要需求依次是综艺、电影和剧集，电视反而其次，所以智能电视和PT 资源是刚需，于是买了大法的电视还有华硕 AC86U 刷梅林。我的 PT （如果需要 HDC 邀请可以找我）就是在路由上装了 transmission 挂个 2T 的远古硬盘（还是刚出 USB3.0 没多久时剁手的），通过梅林 nfs/smb 共享，完全足够家用了，没啥成本都是现成的（哪个程序猿手里还没几块陈年硬盘，梅林用来搭全局代理的梯子、去广告基本也是刚需），可以参考一下。

当初装宽带送 iptv，为了不让运营商赚安装费我就拒绝了，哈哈。其实主要是需求不大，而且多一个不常用的设备不符合个人洁癖。在网上简单调研过 IPTV 的盒子不是必须，而且好像后续想要还可以直接申请，除了安装费也不用花钱。后来也是抱着试一试的态度折腾了一下，也是折腾了好久（确实计算机网络没好好学，很多原理一知半解）终于成功了，过年父母来了还一起看了春晚。

如果只是在手机和平板上有需求，而且是看在线资源的话，kodi 的意义确实不大，尤其 kodi 的播放功能没那么强大，比如倍速播放还得折腾下才勉强能用，还不稳定。kodi 对电视和遥控器的支持比较好，配置好了之后挺适合老人小孩使用，还有刮削器之类的神器，可以自动匹配本地资源，管理起来很方便。倒是也有适配触屏的主题，不过没用过。

去广告我用的是这个：https://github.com/privacy-protection-tools/anti-AD
直接装在路由器的 dnsmasq 规则里然后dhcp 用路由的 dns，简单粗暴去广告还挺彻底的，包括各大视频网站，有些误杀（ios 的盒马 app还有苏宁易购）拖延症还没有抓包去排查

最后再扯回播放列表，我在脚本里是按照那个模板的顺序排列频道的，正好是按照 CCTV，地方卫视，最后是有些混乱地方台和数字付费，后面一坨没匹配上的就直接按照文本排序来了，都不是拼音的顺序，不过整体效果还是挺好的。

对了，我的坐标是西小口，其实还挺近的，有机会说不定可以认识一下~
