### ISSUE TITLE
这个节目是不是错了?

### ISSUE THREAD

**Issue by Sowevo** [wuwentao/bj-unicom-iptv#21]
这个台标是不是错了?
CCTV16的图标,家有购物[高清]的title,节目是BTV的体育休闲,
https://github.com/wuwentao/bj-unicom-iptv/blob/10e88cecbe3c0e878d9bb97c63039f8f80a626ff/bj-unicom-iptv.m3u#L147

**Comment by wuwentao** [comment]
@Sowevo 感谢指正，确实是手抖写错，马上更新

**Comment by wuwentao** [comment]
另外，这个频道现在确实变成BRTV体育休闲频道了，而且BRTV体育休闲频道现在确实是有二个节目源了，目测后续还会变，先保留着地址，随后大概率还会更新。

**Comment by Sowevo** [comment]
👍🏻
