### ISSUE TITLE
缺少部分高清北京台

### ISSUE THREAD

**Issue by alfredfenglq** [wuwentao/bj-unicom-iptv#22]
#EXTINF:-1,BTV科教高清
rtp://239.3.1.115:8000

#EXTINF:-1,BTV财经高清
rtp://239.3.1.116:8000

#EXTINF:-1,BTV生活高清
rtp://239.3.1.117:8000

**Comment by wuwentao** [comment]
@alfredfenglq 非常感谢您的反馈，确实可以使用，我已更新列表！
也欢迎您随后提交pull request一并更新，当然issue也没问题，哈哈！
修改diff见：
https://github.com/wuwentao/bj-unicom-iptv/commit/80ab13f61dd26d22d3de7e797efae426c52cf6cf

**Comment by wuwentao** [comment]
fixed
