### ISSUE TITLE
BRTV体育休闲有台标啦

### ISSUE THREAD

**Issue by David-218** [wuwentao/bj-unicom-iptv#23]
#EXTINF:-1 tvg-id=""  tvg-name="BTRV体育休闲"  group-title="[高清]北京",BRTV体育休闲[高清]
rtp://239.3.1.243:8000

台标URL:
http://epg.51zmt.top:8000/tb1/sheng/BTV%E4%BD%93%E8%82%B2.png

**Comment by wuwentao** [comment]
fixed via #24
