### ISSUE TITLE
cctv 4k频道分组

### ISSUE THREAD

**Issue by icetea0822** [wuwentao/bj-unicom-iptv#26]
请问这个4k频道是不是应该在cctv的分组里更好呀，因为看家里的歌华和电信iptv都是放在cctv的最后一个频道的

**Comment by wuwentao** [comment]
可以，没问题，如果您会改，帮忙提交一个PR增加即可。
或者稍等几天，晚些我再来改也行，最近暂时有些其他事情，会有一些延迟

**Comment by wuwentao** [comment]
@icetea0822 已更新CCTV 4K到央视高清组内
