### ISSUE TITLE
北京联通的IPTV源失效

### ISSUE THREAD

**Issue by chengcic** [wuwentao/bj-unicom-iptv#27]
这两周突然失效了

rtp://239.3.1.1:8000

这个CCTV1的源在笔记本VLC里面无法播放

**Comment by wuwentao** [comment]
我这边也用笔记本播放了，没有任何问题，地址是有效的，CCTV1标清，请确认一下你的环境和其他节目源。
或者换个时间段重新试试？

**Comment by chengcic** [comment]
是的，需要重启路由器。谢谢帮忙确认。
