### ISSUE TITLE
关于光猫的设置

### ISSUE THREAD

**Issue by xxxyangyu** [wuwentao/bj-unicom-iptv#5]
您好，实在不好意思没找到您的联系方式，只能以issue的方式跟您联系。
看了IPTV中继原理，我想问一下光猫是如何设置的。
我也是北京联通，去光猫配置看了一下，跟您截图一模一样。光猫改了桥接模式，主路由拨号。iptv盒子插光猫任意口都可以收看。可问题是我电脑直连光猫，dhcp，获取到192.168.1.x的地址，不能上网因为是桥接模式。（改了路由模式，光猫拨号问题一样）但是理论上应该有组播的信号，但是直连电脑vlc打开直播源并不能收看。所有请问您具体的配置什么样的？是哪里配置问题吗

**Comment by wuwentao** [comment]
请仔细查看：[IPTV.md](https://github.com/wuwentao/bj-unicom-iptv/blob/master/iptv.md)
PC是下挂在路由器的udpxy或者igmp proxy之后的。

如果PC非要直连光猫播放IPTV，还需要做额外配置，组播路由的网段应该不通，需要手工在路由器里添加额外的配置吧，DHCP默认在192.168.1.x网段是光猫内部的LAN，组播IPTV是用的IPoE协议，光猫内部的路由表和配置我没看过，但是DHCP的网络应该和IPTV vlan不通或者vlan id不一样，光猫我也没telnet、ssh权限，查不到内部的vlan和路由信息……

所以还是把PC连接到下挂路由器的方式更可控，因为下挂路由器可以完全操作，并控制中继的协议。
如果光猫完全开放ssh,telnet权限，应该也ok。

或者参考OpenGG的 [北京联通IPTV的完美方案](https://exp.newsmth.net/topic/357dabb5a4dc6d5c4c75f96a30209cd9/1)

**Comment by xxxyangyu** [comment]
查看了iptv.md，光猫的配置跟我的一模一样，界面样式都完全一致。我明白您的意思，实际上我的pc也是下挂在主路由（openwrt）后的。主路由上也设置了igmpproxy，udproxy, 但是完全没有效果(无论光猫是路由模式，还是桥接模式)。路由器端口抓包，只收到了vlc发出来的igmp的包，没有任何其他回包（包括使用udproxy 做http单拨）。所以在查看是否是光猫的问题，因为之前pc直连光猫的时候是会收到组播信号的。所以在怀疑是否是光猫的配置问题。
![image](https://user-images.githubusercontent.com/7440906/83748134-4e76ca80-a694-11ea-8333-7cf32b1ad0a9.png)
![image](https://user-images.githubusercontent.com/7440906/83748181-5fbfd700-a694-11ea-98e8-d5df6069e1f8.png)

**Comment by wuwentao** [comment]
既然设置看起来没毛病，也全部符合，那就更简单了，检查IPTV状态是否可用即可啊！

1. 状态--》 设备信息--》设备基本信息--》业务信息--》IPTV 
然后确认IPv4、IPv6里，是否有可用的IPTV业务

2. 状态--》 网络侧信息--》WAN连接信息--》IPv4
再次确认**4_IPTV_R_VID_3964**是【使能】【已连接】并且DHCP已经分配到地址就ok了（我这里是10.250.x.x的地址，dns是210.x.x.x的）

如果这里都未连接、不正常，DHCP没有地址，那就根本不是下行设置的问题了！
或者连接机顶盒确认是否能看IPTV即可，估计可以找客服报修了
如果这里都正常，就再找下行udpxy和路由器的设置吧

**Comment by xxxyangyu** [comment]
这些都是正常的，iptv拿到了10开头的地址。跟您的一模一样。所以很奇怪这样。机顶盒连接光猫任意口组播点播都没问题，不过还是谢谢您
Thanks!
Best regards,
Yang Yu


Wentao Wu <notifications@github.com> 于2020年6月4日周四 下午10:44写道：

**Comment by wuwentao** [comment]
那说明光猫和上联都正常了，问题在下级路由器和udpxy的配置了，理论上来说，这个玩意应该是很成熟并且很多人都在用的方法了，不会单个不可用啊，除非是有新的变化或者新的修改，但目前看你光猫，你也确认都一样……

**Comment by xxxyangyu** [comment]
所以我无法确认是否是我配置问题，想要电脑直插光猫看看能否直接拿到组播，来确认是否是我路由器设置问题。

**Comment by wuwentao** [comment]
你下挂电脑是验证不了，如果要这么干，电脑也需要启用组播协议并加入相应的组播组，很明显，你还没搞清楚它的原理和组网图，并不是插个电脑，开个播放器或者加个单播路由，就能通或者播放IPTV的！

请再次看组网图，必须有正确的组播协议！不管在啥设备上，机顶盒或者下级路由器，都是需要运行组播协议，所以你的PC压根没有启用组播协议，也没有加入相应的组播组并注册成功，方法错了，还是尽量按正规流程验证。

另外，你这个基本就是下级路由设置问题，机顶盒工作正常，足以说明光猫是没问题的，认证通过，协议监听正常，都可以排除，你用错误的方法在排除并确认光猫设备是否能正常工作，把自己绕晕了而已（虽然它能正常工作，但只是你没有使用正确的验证方法……）

**Comment by xxxyangyu** [comment]
我感觉您说的是错误的，首先光猫设置中已经开启了IGMP proxy, 说明光猫内网（192.168.1.1/24
)内组播信号可达呀。电脑直接连接光猫，采用192.169.1.xx的ip， 组播播放器播放rtp媒体源时，抓包可见igmp v3
join的包。并且在之前的家，也是北京联通，电脑直接连接光猫是可以播放的。
退一步来讲，我换了刷梅林的ac68u做下级路由，光猫桥接拨号，开起来igmpproxy跟udpxy，依然是没有效果的。所以我不得不怀疑是光猫的问题呀。
Thanks!
Best regards,
Yang Yu


Wentao Wu <notifications@github.com> 于2020年6月8日周一 上午11:01写道：

**Comment by xxxyangyu** [comment]
如果可以，希望能有偿的请您帮忙远程设置一下。折腾了好久也没有成功~  wechat: xxxyangyu
