### ISSUE TITLE
关于北京联通IPTV的多终端同时使用

### ISSUE THREAD

**Issue by flagyan** [wuwentao/bj-unicom-iptv#6]
@wuwentao 请问你那边的IPTV支持多终端同时连接吗？我这边用padavan上的udpxy，默认参数已经支持10个并发，不过实际使用时只能同时连接一个终端，如果有新的终端连接之后旧的就会断掉。谢谢。

**Comment by wuwentao** [comment]
@flagyan 
之前试过的，都支持
1. 同一台PC开多个播放器，播放不同的电视节目
2. 多台设备同时开多个不同的电视节目
都是OK的，没有任何问题，并且随着开的连接和视频源增多，带宽占用也会变大，都是验证并测试通过的。

ssh上去看看实际运行的udpxy的参数对不对，卡顿时，考虑增加buffer size之类，会对router的性能有更大的占用

**Comment by flagyan** [comment]
感谢 @wuwentao 
CPU负载和内存应该问题不大
udpxy的参数 udpxy -m eth3.9 -p 4000 -B 65536 -c 10
请问这个参数有问题吗？参数没问题的话只能去看udpxy的详细log了。

**Comment by wuwentao** [comment]
差异可以忽略，基本一样，以下是我的老路由器上的结果：

`
/usr/sbin/udpxy -m eth0 -p 8012 -B 65536 -c 10 -a br0
`

```
xxx@xxx:/tmp/home/root# /usr/sbin/udpxy -v
udpxy 1.0-23.10 (prod) standard [Linux 2.6.36.4brcmarm armv7l]
usage: /usr/sbin/udpxy [-vTS] [-a listenaddr] -p port [-m mcast_ifc_addr] [-c clients] [-l logfile] [-B sizeK] [-n nice_incr]
	-v : enable verbose output [default = disabled]
	-S : enable client statistics [default = disabled]
	-T : do NOT run as a daemon [default = daemon if root]
	-a : (IPv4) address/interface to listen on [default = 0.0.0.0]
	-p : port to listen on
	-m : (IPv4) address/interface of (multicast) source [default = 0.0.0.0]
	-c : max clients to serve [default = 3, max = 5000]
	-l : log output to file [default = stderr]
	-B : buffer size (65536, 32Kb, 1Mb) for inbound (multicast) data [default = 2048 bytes]
	-R : maximum messages to store in buffer (-1 = all) [default = 1]
	-H : maximum time (sec) to hold data in buffer (-1 = unlimited) [default = 1]
	-n : nice value increment [default = 0]
	-M : periodically renew multicast subscription (skip if 0 sec) [default = 0 sec]
Examples:
  /usr/sbin/udpxy -p 4022
	listen for HTTP requests on port 4022, all network interfaces
  /usr/sbin/udpxy -a lan0 -p 4022 -m lan1
	listen for HTTP requests on interface lan0, port 4022;
	subscribe to multicast groups on interface lan1

  udpxy and udpxrec are Copyright (C) 2008-2013 Pavel V. Cherenkov and licensed under GNU GPLv3
  Contact: www.udpxy.com/forum; support@udpxy.com

xxxx@xxx:/tmp/home/root#
```

多个连接的时候，web版的status里面是能显示多个active的连接信息的

**Comment by flagyan** [comment]
今天把udpxy的log保存看了一下，确实在log里面看到下面这类log：
2020-06-14 18:27:13.229922 CST	c(19291)	multicast-group [ADD]
2020-06-14 18:27:13.265757 CST	c(19291)	multicast-group [DROP]
而且一个连接就会出现几次，在新连接接入的时候老的会DROP，具体log有点多，我没看明白具体的连接流程。

udpxy -l /tmp/u.log -m eth3.9 -p 4000 -B 65535 -c 10

[udpxy.log](https://github.com/wuwentao/bj-unicom-iptv/files/4776576/udpxy.log)

@wuwentao 你对udpxy的具体流程了解吗？如果可以的话请帮忙看一下log，如果也没研究过请把这个issue关闭吧，感谢。

**Comment by wuwentao** [comment]
@flagyan 不好意思，udpxy的流程和log还真没仔细看过，主要是一直工作正常，所以就压根没看过这玩意了！
udpxy有不少github的地址，你可以去搜索一下！
只是解决问题的话，那排除法、替换法可能是最傻但最简单且直接有效的故障解决方法。
